#!/bin/bash

##############################################################################
# Helper functions
##############################################################################

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source $TEST_DIR/lib/common-utils

##############################################################################
# Check the plaftorm
##############################################################################

get_platform_host

##############################################################################
# Check the existance of configuration files
##############################################################################

SERVICES_FILE=$TEST_DIR/services.yaml
NODES_FILE=$TEST_DIR/log/nodes.yaml

if [[ ! -f $SERVICES_FILE ]]; then
    echo "Please create a 'services.yaml' file with the list of services to be deployed."
    echo "Use the 'services.yaml.sample' file as a template"
    exit 1
fi

if [[ ! -f $NODES_FILE ]]; then
    echo "Run start first. Could not find file with nodes config."
    exit 1
fi

##############################################################################
# Deploy and link all I/O and reconstruction services
##############################################################################

DEPLOYER=std.orchestrators.DefaultDeploy
runClara $DEPLOYER $NODES_FILE $SERVICES_FILE
