#!/bin/bash

##############################################################################
# Helper functions
##############################################################################

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source $TEST_DIR/lib/common-utils


function orchestrator()
{
    rm -f $2
    sleep 1

    runClara std.orchestrators.DefaultOrchestrator $1 $2 $3 $4
}

##############################################################################
# Check the plaftorm
##############################################################################

get_platform_host

##############################################################################
# Check the nodes
##############################################################################

NODES_LIST=""
NODES_FILE=$TEST_DIR/log/nodes.yaml

if [[ ! -f $NODES_FILE ]]; then
    echo "Run 'start' first. Could not find file with nodes list."
    exit
fi

##############################################################################
# Options
##############################################################################

function usage()
{
    echo "Usage:"
    echo -e "\t$0 <input_file> <output_file> <num_cores> [ <num_nodes> ]"
}


while getopts “h” OPTION
do
    case $OPTION in
        h)
            usage; exit 0 ;;
        ?)
            echo; usage; exit 1 ;;
    esac
done

shift $((OPTIND-1))
if [[ $# -lt 3  || $# -gt 4 ]]; then
    usage
    exit 1
fi

##############################################################################
# Check arguments
##############################################################################

INFILE="$1"
OUTFILE="$2"
CORES=$3
NODES=0
if [[ $# -eq 4 ]]; then
    NODES=$4
fi

if [[ ! -f "$INFILE" ]]; then
    echo "Input files doesn't exist."
    exit 1
fi

if [[ $PLATFORM_HOST == "head" ]]; then
    MAX_CORES=12
else
    MAX_CORES=32
fi
if [[ $CORES -lt 1 || $CORES -gt $MAX_CORES ]]; then
    echo "Wrong number of cores: $CORES"
    exit 1
fi

if [[ $NODES -lt 0 || $NODES -gt $(wc -l $NODES_FILE | cut -d' ' -f 1) ]]; then
    echo "Wrong number of nodes: $NODES"
    exit 1
fi

##############################################################################
# Generate the list of DPEs
##############################################################################

counter=0
parser=std.orchestrators.ProductionConfigParser
while read NODE
do
    NODES_LIST="$NODES_LIST $NODE "
    let counter=counter+1
    if [[ $counter -eq $NODES ]]; then
        break
    fi
done < <(runClara $parser parse-nodes reconstruction $NODES_FILE)

##############################################################################
# Launch DefaultOrchestrator
##############################################################################

orchestrator "$INFILE" "$OUTFILE" "$CORES" "$NODES_LIST"
