#!/usr/bin/env bash

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

##############################################################################
# Launch local orchestrator
##############################################################################

source $TEST_DIR/lib/common-utils
set_classpath

MAIN=org.jlab.clas.std.orchestrators.LocalOrchestrator

java -cp $CLASSPATH $MAIN "$@" 2>&1 | tee $TEST_DIR/log/run-local.log

exit ${PIPESTATUS[0]}
