#!/usr/bin/env bash

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

##############################################################################
# Launch local orchestrator
##############################################################################

"$CLARA_HOME/bin/clara-orchestrator" "$@" 2>&1 | tee $TEST_DIR/log/run-local.log

exit ${PIPESTATUS[0]}
