#!/usr/bin/env bash

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

##############################################################################
# Launch cloud orchestrator
##############################################################################

"$CLARA_HOME/bin/clara-orchestrator" -C "$@" 2>&1 | tee $TEST_DIR/log/run-cloud.log

exit ${PIPESTATUS[0]}
