#!/usr/bin/env bash

test_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p $test_dir/log

##############################################################################
# Launch cloud orchestrator
##############################################################################

"$CLARA_HOME/bin/clara-orchestrator" -C "$@" 2>&1 | tee $test_dir/log/run-cloud.log

exit ${PIPESTATUS[0]}
