#!/usr/bin/env bash

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

##############################################################################
# Launch local orchestrator
##############################################################################

CLASSPATH="$CLARA_HOME/lib/*:$CLARA_HOME/services/*"
MAIN=org.jlab.clas.std.orchestrators.LocalOrchestrator

java -cp $CLASSPATH $MAIN "$@" 2>&1 | tee $TEST_DIR/log/run-local.log

exit ${PIPESTATUS[0]}
