#!/bin/bash

##############################################################################
# Helper functions
##############################################################################

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source $TEST_DIR/lib/clara-wrapper
source $TEST_DIR/lib/common-utils


function orchestrator()
{
    rm -f $2
    sleep 1

    runClara std.orchestrators.ProductionOrchestrator $3 $1 $2
}

##############################################################################
# Check the plaftorm
##############################################################################

get_platform_host

##############################################################################
# Check the services
##############################################################################

SERVICES_FILE=$TEST_DIR/services

if [[ ! -f $SERVICES_FILE ]]; then
    echo "Please create a 'services' file with the list of services to be deployed."
    echo "Use the 'services.sample' file as a template"
    exit 1
fi

##############################################################################
# Options
##############################################################################

function usage()
{
    echo "Usage:"
    echo -e "\t$0 <input_file> <output_file>"
}


while getopts “h” OPTION
do
    case $OPTION in
        h)
            usage; exit 0 ;;
        ?)
            echo; usage; exit 1 ;;
    esac
done

shift $((OPTIND-1))
if [[ ! $# -eq 2 ]]; then
    usage
    exit 1
fi

##############################################################################
# Check arguments
##############################################################################

INFILE="$1"
OUTFILE="$2"

if [[ ! -f "$INFILE" ]]; then
    echo "Input file doesn't exist."
    exit 1
fi

##############################################################################
# Launch the orchestrator
##############################################################################

orchestrator "$INFILE" "$OUTFILE" "$SERVICES_FILE"
