#!/bin/bash

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source $TEST_DIR/lib/clara-wrapper


function orchestrator()
{
    rm -f $2
    sleep 1

    runClara std.orchestrators.ProductionOrchestrator $3 $1 $2
}


function usage()
{
    echo "Usage:"
    echo -e "\t$0 <input_file> <output_file>"
}


PLATFORM_HOST=$(hostname -s)

if [[ $PLATFORM_HOST != "head" && $PLATFORM_HOST != "claradm" ]]; then
    echo "This scripts should run in head (UofR cluster) or claradm"
    exit 1
fi


while getopts “h” OPTION
do
    case $OPTION in
        h)
            usage; exit 1 ;;
        ?)
            echo; usage; exit 1 ;;
    esac
done

shift $((OPTIND-1))
if [[ ! $# -eq 2 ]]; then
    usage
    exit 1
fi

SERVICES_FILE=$TEST_DIR/services

if [[ ! -f $SERVICES_FILE ]]; then
    echo "Please create a 'services' file with the list of services to be deployed."
    echo "Use the 'services.sample' file as a template"
    exit 1
fi

INFILE="$1"
OUTFILE="$2"

if [[ ! -f "$INFILE" ]]; then
    echo "Input file doesn't exist."
    exit 1
fi

orchestrator "$INFILE" "$OUTFILE" "$SERVICES_FILE"
