#!/bin/bash

##############################################################################
# Options
##############################################################################

function usage()
{
    echo "Usage:"
    echo -e "\t$0 <services_file> <input_file> <output_file>"
}


while getopts “hl:” OPTION
do
    case $OPTION in
        l)
            LOOPS=$OPTARG ;;
        h)
            usage; exit 0 ;;
        ?)
            echo; usage; exit 1 ;;
    esac
done

shift $((OPTIND-1))
if [[ ! $# -eq 3 ]]; then
    usage
    exit 1
fi

if [[ -z $LOOPS ]]; then
    LOOPS=10
fi

##############################################################################
# Launch ProductionOrchestrator
##############################################################################

${CLARA_SERVICES}/bin/production-orchestrator -l $LOOPS "$@"
