#!/bin/bash

##############################################################################
# Options
##############################################################################

usage()
{
    cat << EOF
usage:

    $(basename $0) <services> <input-files>

options:

    -i <input_files_dir>        --  location of the input files
                                    (default: \$CLARA_SERVICES/data/in)

    -o <output_files_dir>       --  location of the output files
                                    (default: \$CLARA_SERVICES/data/out)

    -s <staging_dir>            --  local directory to put temporary files
                                    (default: /scratch)

    -l <#_of_rec_loops>         --  number of times that the list of input
                                    files should be processed (default: 1)
EOF
}


while getopts "hi:o:s:l:" OPTION
do
    case $OPTION in
        h)
            usage; exit 0 ;;
        i)
            INPUT_DIR=$OPTARG ;;
        o)
            OUTPUT_DIR=$OPTARG ;;
        s)
            STAGE_DIR=$OPTARG ;;
        l)
            LOOPS=$OPTARG ;;
        ?)
            echo; usage; exit 1 ;;
    esac
done

shift $((OPTIND-1))
if [ ! "$#" = 2 ]; then
    usage
    exit 1
fi

if [ -z "$INPUT_DIR" ]; then
    INPUT_DIR="$CLARA_SERVICES/data/in"
fi

if [ -z "$OUTPUT_DIR" ]; then
    OUTPUT_DIR="$CLARA_SERVICES/data/out"
fi

if [ -z "$STAGE_DIR" ]; then
    STAGE_DIR=/scratch
fi

if [ -z "$LOOPS" ]; then
    LOOPS=1
fi

##############################################################################
# Launch FarmOrchestrator
##############################################################################

${CLARA_SERVICES}/bin/farm-orchestrator \
        -i "$INPUT_DIR"\
        -o "$OUTPUT_DIR"\
        -s "$STAGE_DIR"\
        -l $LOOPS\
        "$1" "$2"
