#!/usr/bin/env bash

##############################################################################
# Helper functions
##############################################################################

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SESSION=TEST

source $TEST_DIR/lib/common-utils


function start_platform()
{
    $TMUX -f $TEST_DIR/lib/tmux.conf new-session -s "$SESSION" -n orchestrator -d
    $TMUX new-window -d -t "$SESSION" -n "extra"
    $TMUX new-window -d -t "$SESSION" -n "platform"
    $TMUX send-keys -R -t "$SESSION:platform" "$TEST_DIR/lib/run-platform $CLARA_SERVICES" "C-m"
}


function start_dpe()
{
    $TMUX new-window -d -t "$SESSION" -n "$1"
    $TMUX send-keys -R -t "$SESSION:$1" "ssh -t $1" "C-m"
    $TMUX send-keys -R -t "$SESSION:$1" "$TEST_DIR/lib/run-dpe $PLATFORM_HOST $CLARA_SERVICES" "C-m"
}

##############################################################################
# Check the plaftorm
##############################################################################

check_tmux
get_platform_host

##############################################################################
# Options
##############################################################################

function usage()
{
    echo -e "Usage:"
    echo -e "\t$0 [ <dpe> ]"
}


KEEP_DETACHED=1
DRY_RUN=1
while getopts "hdp:n" OPTION
do
    case $OPTION in
        h)
            usage; exit 0 ;;
        d)
            KEEP_DETACHED=0 ;;
        n)
            DRY_RUN=0 ;;
        ?)
            echo; usage; exit 1 ;;
    esac
done

##############################################################################
# Start the platform and the DPEs
##############################################################################

shift $((OPTIND-1))
if [[ $# -eq 0 ]]; then
    $TEST_DIR/quit
    cd $TEST_DIR
    rm -rf $TEST_DIR/log
    mkdir -p $TEST_DIR/log
    echo "Starting platform on local node $PLATFORM_HOST"
    if [[ $DRY_RUN -eq 1 ]]; then
        start_platform
        sleep 1
    else
        exit 0
    fi
    if [[ $KEEP_DETACHED -eq 1 ]]; then
        $TMUX select-window -t "$SESSION:orchestrator"
        $TMUX -2 attach-session -t "$SESSION"
    fi
elif [[ $# -eq 1 ]]; then
    echo "Starting DPE on $1 (with platform in $PLATFORM_HOST)..."
    if [[ $DRY_RUN -eq 1 ]]; then
        start_dpe $1
    fi
else
    usage
    exit 1
fi
