#!/bin/bash

##############################################################################
# Helper functions
##############################################################################

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SESSION=TEST

source $TEST_DIR/lib/common-utils


function start_platform()
{
    screen -d -m -S $SESSION -c $TEST_DIR/lib/screenrc
    screen -S $SESSION -X screen 1
    sleep 1
    screen -S $SESSION -X screen -t platform $TEST_DIR/lib/run-platform $CLARA_SERVICES
}


function start_dpe()
{
    screen -S $SESSION -X screen -t $1
    sleep .01
    screen -S $SESSION -X other
    screen -S $SESSION -p $1 -X stuff "ssh -t $1 $TEST_DIR/lib/run-dpe $PLATFORM_HOST $CLARA_SERVICES"
}

##############################################################################
# Check the plaftorm
##############################################################################

check_screen
get_platform_host

##############################################################################
# Options
##############################################################################

function usage()
{
    echo -e "Usage:"
    echo -e "\t$0 [ <dpe> ]"
}


KEEP_DETACHED=1
DRY_RUN=1
while getopts "hdn" OPTION
do
    case $OPTION in
        h)
            usage; exit 0 ;;
        d)
            KEEP_DETACHED=0 ;;
        n)
            DRY_RUN=0 ;;
        ?)
            echo; usage; exit 1 ;;
    esac
done

##############################################################################
# Start the platform and the DPEs
##############################################################################

shift $((OPTIND-1))
if [[ $# -eq 0 ]]; then
    $TEST_DIR/quit
    cd $TEST_DIR
    rm -rf $TEST_DIR/log
    mkdir -p $TEST_DIR/log
    echo "Starting platform on local node $PLATFORM_HOST"
    if [[ $DRY_RUN -eq 1 ]]; then
        start_platform
        sleep 1
    else
        exit 0
    fi
    if [[ $KEEP_DETACHED -eq 1 ]]; then
        screen -r -S $SESSION -p 0
    fi
elif [[ $# -eq 1 ]]; then
    echo "Starting DPE on $1 (with platform in $PLATFORM_HOST)..."
    if [[ $DRY_RUN -eq 1 ]]; then
        start_dpe $1
    fi
else
    usage
    exit 1
fi
