#!/bin/bash

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SESSION=TEST

source $TEST_DIR/lib/clara-wrapper
source $TEST_DIR/lib/common-utils

get_platform_host


function start_platform()
{
    cat /dev/null > $TEST_DIR/nodes
    screen -d -m -S $SESSION -c $TEST_DIR/lib/screenrc
    echo "Starting platform..."
    screen -S $SESSION -X screen -t platform $TEST_DIR/lib/run-platform
    sleep 2
}


function start_dpe()
{
    screen -S $SESSION -X screen -t $1 ssh -t $1 $TEST_DIR/lib/run-dpe
    sleep 0.25
}


function launch()
{
    cd $TEST_DIR
    rm -rf $TEST_DIR/log
    mkdir -p $TEST_DIR/log

    start_platform

    if [[ $NUMBER_OF_NODES -eq 0 ]]; then
        echo $PLATFORM_HOST >> $TEST_DIR/nodes
    else
        local counter=$FIRST_NODE
        local last=$(($FIRST_NODE+$NUMBER_OF_NODES))
        while [[ $counter -lt $last ]]; do
            case $counter in
                [1-9])    node="physics0$counter"   ;;
                1[0-6])   node="physics$counter"    ;;
            esac
            echo "Starting DPE on $node..."
            echo $node >> $TEST_DIR/nodes
            start_dpe $node
            let counter=counter+1
        done
    fi

    sleep 1
    if [[ $KEEP_DETACHED -eq 1 ]]; then
        screen -r -S $SESSION -p 0
    fi
}


function usage()
{
    echo -e "Usage:"
    echo -e "\t$0 [-s <first_node> ] <nodes>"
}


FIRST_NODE=1
KEEP_DETACHED=1
while getopts “hdfs:” OPTION
do
    case $OPTION in
        h)
            usage; exit 0 ;;
        d)
            KEEP_DETACHED=0 ;;
        s)
            FIRST_NODE=$OPTARG ;;
        ?)
            echo; usage; exit 1 ;;
    esac
done

shift $((OPTIND-1))
if [[ ! $# -eq 1 ]]; then
    usage
    exit 1
fi
NUMBER_OF_NODES=$1

if [[ $PLATFORM_HOST == "head" ]]; then
    MAX_NODES=12
    if [[ $FIRST_NODE -lt 1 || $FIRST_NODE -gt $MAX_NODES ]]; then
        echo "Wrong node number: $FIRST_NODE"
        exit 1;
    fi
else
    MAX_NODES=0
fi
if [[ $NUMBER_OF_NODES -lt 0 || $NUMBER_OF_NODES -gt $MAX_NODES ]]; then
    echo "Wrong node number: $NUMBER_OF_NODES"
    exit 1;
fi

# Remove any existing screen session first
$TEST_DIR/quit

# Start the platform and the DPEs
launch
