# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 :

require 'yaml'
require 'pathname'

if File.exist?('custom-config.yaml')
  test_conf = YAML.load_file('custom-config.yaml')
else
  test_conf = YAML.load_file('default-config.yaml')
end

src_dir = test_conf["srcdir"]
clara_nodes = test_conf["nodes"]


Vagrant.require_version ">= 1.4"

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  clara_nodes.each do | node_name, node_ip |
    config.vm.define node_name do | node_config |

      node_config.vm.box = "ubuntu/trusty64"
      node_config.vm.hostname = node_name.to_s
      node_config.vm.network :private_network, ip: node_ip
      node_config.ssh.forward_agent = true
      node_config.ssh.forward_x11 = true

      node_config.vm.synced_folder "..", "/vagrant"
      dev_dir = "/home/vagrant/clara/dev"
      node_config.vm.synced_folder src_dir, dev_dir

      node_config.vm.provision :shell, :path => "provision/apt-bootstrap.sh"

      node_config.vm.provision :puppet do | puppet |
        puppet.manifests_path = "provision/manifests"
        puppet.manifest_file = "default.pp"
        puppet.module_path = "provision/modules"
        puppet.options = "--verbose --debug"
      end

      # Copy Git user info to VM
      git_name = `git config user.name`.chomp
      git_email = `git config user.email`.chomp
      if not git_name.empty? and not git_email.empty?
        script = %{
            echo 'Setting Git user...' &&
            git config --file ~/.config/git/local user.name '#{git_name.chomp}' &&
            git config --file ~/.config/git/local user.email '#{git_email.chomp}'
        }.gsub(/\s+/, " ").strip
        node_config.vm.provision :shell, :inline => script, :privileged => false
      else
        node_config.vm.provision :shell, :inline => "echo 'Git user not set!' >&2"
      end

    end
  end
end
