#!/usr/bin/env bash

function check_tmux()
{
    command -v tmux >/dev/null 2>&1 ||
        { echo "tmux it's not installed. Aborting."; exit 1; }
}


function run_clara()
{
    java -cp "$CLARA_HOME/.:$CLARA_HOME/lib/*" $*
}


function get_fe_host()
{
    FE_HOST=$(hostname -s)
}


function get_mail()
{
    local test_dir=$1
    if [[ -f $test_dir/mail ]]; then
        MAILTO=$(cat $test_dir/mail)
    else
        MAILTO=${USER}@jlab.org
    fi
}
