#!/usr/bin/env bash

function check_tmux()
{
    command -v tmux >/dev/null 2>&1 ||
        { echo "tmux it's not installed. Aborting."; exit 1; }
}


function run_clara()
{
    java -cp "$CLARA_HOME/.:$CLARA_HOME/lib/*" $*
}


function get_fe_host()
{
    FE_HOST=$(hostname -s)
}


function contains()
{
    local e
    for e in "${@:2}"; do
        [[ "$e" == "$1" ]] && return 0;
    done
    return 1
}
