#!/bin/bash

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."

source $TEST_DIR/lib/clara-wrapper

SERVICES_FILE=$TEST_DIR/services

if [[ ! -f $SERVICES_FILE ]]; then
    echo "Please create a file with the list of services to be deployed."
    exit
fi

DPE_HOST=$(hostname -i)

READER_ENGINE=$1
WRITER_ENGINE=$2

PREVIOUS_ENGINE=$READER_ENGINE

tmp_services=$(/bin/mktemp)
grep -v '^\s*#' $SERVICES_FILE > $tmp_services

while IFS=$' ' read -r -a myService
do
    SERVICE_CLASS=${myService[0]}
    CONTAINER=${myService[1]}
    deploy $DPE_HOST $CONTAINER $SERVICE_CLASS
done < $tmp_services

sleep 1

while IFS=$' ' read -r -a myService
do
    CONTAINER=${myService[1]}
    SERVICE_ENGINE=$DPE_HOST/$CONTAINER/${myService[2]}
    link $PREVIOUS_ENGINE $SERVICE_ENGINE
    PREVIOUS_ENGINE=$SERVICE_ENGINE
    echo
done < $tmp_services

rm $tmp_services

link $PREVIOUS_ENGINE $WRITER_ENGINE
