#!/bin/bash

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."

source $TEST_DIR/lib/clara-wrapper

SERVICES_FILE=$TEST_DIR/services

if [[ ! -f $SERVICES_FILE ]]; then
    echo "Please create a file with the list of services to be deployed."
    exit
fi

DPE_HOST=($(hostname -i))

tmp_services=$(/bin/mktemp)
grep -v '^\s*#' $SERVICES_FILE > $tmp_services

while IFS=$' ' read -r -a myService
do
    SERVICE_CLASS=${myService[0]}
    CONTAINER=${myService[1]}
    deploy ${DPE_HOST[0]} $CONTAINER $SERVICE_CLASS
done < $tmp_services

rm $tmp_services
