#!/usr/bin/env bash

test_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."

CLARA_HOME=$1
CLAS12DIR=$1/plugins/clas12

export CLARA_HOME
export CLAS12DIR

fe_host=$2

"$CLARA_HOME"/bin/j_dpe --fe-host "$fe_host" 2>&1 | tee "$test_dir/log/$HOSTNAME.log"
