#!/usr/bin/env bash

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."

CLARA_HOME=$1
CLAS12DIR=$1/plugins/clas12
FE_HOST=$2

export CLARA_HOME
export CLAS12DIR

$CLARA_HOME/bin/j_dpe --host $FE_HOST 2>&1 | tee $TEST_DIR/log/fe.log
